import { useEffect, useRef, useState } from 'react';
import { ArrowUp, Film, Gamepad2, Sparkles, Plus, Copy, Check } from 'lucide-react';
import { api } from '../api';
import { useAuth } from '../AuthContext';
import { Alert, formatNumber } from '../components/UI';
const suggestions = [['Cine para esta noche','¿Cuáles son 3 películas de drama?',Film],['Una nueva aventura','¿Cuáles son 2 videojuegos de aventura?',Gamepad2],['Los mejor valorados','¿Qué juegos de disparos tienen una calificación mayor a 8.5?',Sparkles]];
export default function Chat({ messages, setMessages }) {
  const { user } = useAuth(); const [question,setQuestion] = useState(''); const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [pending,setPending] = useState(''); const [copied,setCopied] = useState(null);
  const end=useRef(null); const field=useRef(null); const inFlight=useRef(false); const controller=useRef(null);
  useEffect(() => { end.current?.scrollIntoView({behavior:'smooth',block:'end'}); }, [messages,busy]);
  useEffect(() => () => controller.current?.abort(), []);
  async function send(e) {
    e.preventDefault(); const text=question.trim(); if (!text || inFlight.current) return;
    inFlight.current=true; setBusy(true); setPending(text); setError(''); controller.current=new AbortController();
    try { const result=await api('/chat',{method:'POST',body:{pregunta:text},signal:controller.current.signal}); setMessages(prev => [...prev,result]); setQuestion(''); }
    catch(error) { if(error.name!=='AbortError') setError(error.message); }
    finally { inFlight.current=false; setBusy(false); setPending(''); field.current?.focus(); }
  }
  async function copy(text,id) { try { await navigator.clipboard.writeText(text); setCopied(id); setTimeout(() => setCopied(null),2000); } catch { setError('No se pudo copiar. Puedes seleccionar el texto de la respuesta.'); } }
  return <div className="chat-page"><header className="chat-header"><div><strong>Tu asistente de catálogo</strong><span>Películas y videojuegos</span></div><button className="secondary" disabled={busy || !messages.length} onClick={() => {setMessages([]);setError('');setQuestion('');}}><Plus size={16}/>Limpiar pantalla</button></header><section className="chat-scroll" aria-label="Conversación"><div className="chat-inner">{!messages.length && !busy && <div className="chat-welcome"><div className="welcome-icon"><Sparkles size={30}/></div><p className="eyebrow">TU PRÓXIMO DESCUBRIMIENTO</p><h1>Hola, {user.nombre.split(' ')[0]}.<br/>¿Qué te gustaría explorar?</h1><p className="muted">Desde un clásico del cine hasta tu siguiente aventura.<br/>Pregúntame sobre las películas y videojuegos del catálogo.</p><div className="suggestions">{suggestions.map(([title,text,Icon]) => <button key={title} onClick={() => {setQuestion(text);field.current?.focus();}}><Icon size={21}/><strong>{title}</strong><span>{text}</span></button>)}</div></div>}{messages.map((item,index) => <div className="exchange" key={`${item.id_conversacion}-${index}`}><div className="user-message"><span className="message-label">TÚ</span><p>{item.pregunta}</p></div><div className="assistant-message"><div className="assistant-icon"><Sparkles size={19}/></div><div><span className="message-label">CINE & PLAY</span><p className="answer-text">{item.respuesta}</p><div className="answer-meta"><span>{item.categoria === 'ambas' ? 'Películas y videojuegos' : item.categoria === 'peliculas' ? 'Películas' : 'Videojuegos'} · {formatNumber(item.tokens)} palabras procesadas</span><button className="icon-button" aria-label="Copiar respuesta" onClick={() => copy(item.respuesta,index)}>{copied===index ? <Check size={16}/> : <Copy size={16}/>}</button></div></div></div></div>)}{busy && <div className="exchange"><div className="user-message"><span className="message-label">TÚ</span><p>{pending}</p></div><div className="assistant-message" role="status"><div className="assistant-icon"><Sparkles size={19}/></div><div><span className="message-label">CONSULTANDO TU CATÁLOGO</span><div className="thinking"><i/><i/><i/></div></div></div></div>}<div ref={end}/></div></section><div className="composer-area"><div className="composer-inner"><Alert>{error}</Alert><form className="composer" onSubmit={send}><textarea ref={field} aria-label="Tu pregunta" placeholder="Pregunta sobre películas o videojuegos…" maxLength={4000} rows={2} value={question} disabled={busy} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter' && !e.shiftKey && !e.nativeEvent.isComposing){e.preventDefault();send(e);}}}/><button className="send-button" aria-label="Enviar pregunta" disabled={busy || !question.trim()}><ArrowUp size={22}/></button></form><p className="composer-note">Cada pregunta es independiente. Puedes revisar tus consultas en Historial.</p></div></div></div>;
}
